=== Mykhailenko/programming/src/org/objectweb/proactive/core/component/xml/components.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--


    ROOT ELEMENTS-->
    <xs:element name="componentsDescriptor">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="types"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="components"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="bindings"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="componentTypeKey">
            <xs:selector xpath="types/component-type"/>
            <xs:field xpath="@name"/>
        </xs:key>
        <xs:keyref name="componentTypeKeyRefPrimitive" refer="componentTypeKey">
            <xs:selector xpath="components/primitive-component"/>
            <xs:field xpath="@type"/>
        </xs:keyref>
        <xs:keyref name="componentTypeKeyRefComposite" refer="componentTypeKey">
            <xs:selector xpath="components/composite-component"/>
            <xs:field xpath="@type"/>
        </xs:keyref>
        <xs:keyref name="componentTypeKeyRefParallel" refer="componentTypeKey">
            <xs:selector xpath="components/parallel-composite-component"/>
            <xs:field xpath="@type"/>
        </xs:keyref>
    </xs:element>
    <xs:element name="types">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="1" ref="component-type"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="component-type" type="componentType"/>
    <!--


    COMPONENTS -->
    <xs:element name="components">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="primitive-component"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="composite-component"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="parallel-composite-component"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!--


    COMPONENT DEFINITIONS (PRIMITIVE AND COMPOSITE) -->
    <xs:element name="primitive-component">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="type" type="xs:string" use="required"/>
            <xs:attribute name="implementation" type="xs:string" use="required"/>
            <xs:attribute name="virtualNode" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <!--

    -->
    <xs:element name="composite-component">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="1" minOccurs="1" ref="components"/>
                <xs:element maxOccurs="1" minOccurs="1" ref="bindings"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="type" type="xs:string" use="required"/>
            <xs:attribute name="virtualNode" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="parallel-composite-component">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="1" minOccurs="1" ref="components"/>
                <xs:element maxOccurs="1" minOccurs="0" ref="bindings"/>
                <!-- bindings are automatic between interfaces of the same name :
													-> primitive1.itfA
							parallel-composite.itfA -> primitive2.itfA
													-> primitive3.itfA
										
						<xs:element maxOccurs="1" minOccurs="1" ref="bindings"/>
						-->
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="type" type="xs:string" use="required"/>
            <xs:attribute name="virtualNode" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <!--


    TYPES
    -->
    <xs:complexType name="componentType">
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="1" name="provides" type="port"/>
            <xs:element maxOccurs="1" minOccurs="0" name="requires" type="port"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="port">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="interface"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="interface">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="signature" type="xs:string" use="required"/>
            <xs:attribute default="mandatory" name="contingency" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="mandatory"/>
                        <xs:enumeration value="optional"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute default="single" name="cardinality" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="single"/>
                        <xs:enumeration value="collection"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <!--


    BINDINGS -->
    <xs:element name="bindings">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="binding"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="binding">
        <xs:complexType>
            <xs:attribute name="client">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value=".*\..*"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="server">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value=".*\..*"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Mykhailenko/programming/src/nonregressiontest/component/descriptor/componentsDescriptor.xml
<?xml version="1.0" encoding="UTF-8"?>
<componentsDescriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../org/objectweb/proactive/core/component/xml/components.xsd">
    <types>
        <component-type name="B-Type">
            <provides>
                <interface name="i2" signature="nonregressiontest.component.I2"/>
            </provides>
        </component-type>
        <component-type name="A-Type" >
            <!-- extends attribute to allow! -->
            <provides>
                <interface name="i1" signature="nonregressiontest.component.I1"/>
            </provides>
            <requires>
                <interface name="i2" signature="nonregressiontest.component.I2"/>
            </requires>
        </component-type>
    </types>
    <components>
        <primitive-component implementation="nonregressiontest.component.PrimitiveComponentB"
            name="p2" type="B-Type" virtualNode="Dispatcher1-AC"/>
        <composite-component name="c" type="A-Type" virtualNode="Dispatcher1-AC">
            <components>
                <primitive-component
                    implementation="nonregressiontest.component.PrimitiveComponentA" name="p1"
                    type="A-Type" virtualNode="Dispatcher1-AC"/>
            </components>
            <bindings>
                <binding client="c.i1" server="p1.i1"/>
                <binding client="p1.i2" server="c.i2"/>
            </bindings>
        </composite-component>
    </components>
    <bindings>
        <binding client="c.i2" server="p2.i2"/>
    </bindings>
</componentsDescriptor>

=== Mykhailenko/programming/src/org/objectweb/proactive/examples/components/helloworld/helloworld-distributed.xml
<?xml version="1.0" encoding="UTF-8"?>
<componentsDescriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../core/component/xml/components.xsd">
	
	<!-- DEFINITION OF THE COMPONENT TYPES -->
	<types>
		<component-type name="RootType">
			<provides>
				<interface name="m" signature="org.objectweb.proactive.examples.components.helloworld.Main"/>
			</provides>
		</component-type>

<!-- extends is not supported yet -->
		<component-type name="ClientType">
			<provides>
				<interface name="m" signature="org.objectweb.proactive.examples.components.helloworld.Main"/>
			</provides>
			<requires>
				<interface name="s" signature="org.objectweb.proactive.examples.components.helloworld.Service"/>
			</requires>
		</component-type>
		
		<component-type name="ServerType">
			<provides>
				<interface name="s" signature="org.objectweb.proactive.examples.components.helloworld.Service"/>
			</provides>
		</component-type>
	
	</types>
	
	<!-- DEFINITION OF THE COMPONENT INSTANCES -->
	<!-- For conveniency (to avoid multiple files), both configurations (with or without wrappers) are 
		defined here, and therefore instantiated and deployed when parsing the file.-->

	<components>
	<!-- standard client server example -->
		<composite-component name="ClientServer" type="RootType" virtualNode="null">
			<components>
				<primitive-component name="client" type="ClientType" implementation="org.objectweb.proactive.examples.components.helloworld.ClientImpl" virtualNode="VN1"/>
				<primitive-component name="server" type="ServerType" implementation="org.objectweb.proactive.examples.components.helloworld.ServerImpl" virtualNode="VN2"/>
			</components>
			<bindings>
				<binding client="ClientServer.m" server="client.m"/>
				<binding client="client.s" server="server.s"/>
			</bindings>
		</composite-component>
	
	<!-- client server examples with wrapped client and server -->
		<composite-component name="ClientServerWrapper" type="RootType">
			<components>
				<composite-component name="clientWrapper" type="ClientType">
					<components>
						<primitive-component name="wrapped-client" type="ClientType" implementation="org.objectweb.proactive.examples.components.helloworld.ClientImpl" virtualNode="VN1"/>
					</components>
					<bindings>
						<binding client="clientWrapper.m" server="wrapped-client.m"/>
						<binding client="wrapped-client.s" server="clientWrapper.s"/>
					</bindings>
				</composite-component>
				<composite-component name="serverWrapper" type="ServerType">
					<components>
						<primitive-component name="wrapped-server" type="ServerType" implementation="org.objectweb.proactive.examples.components.helloworld.ServerImpl" virtualNode="VN2"/>
					</components>
					<bindings>
						<binding client="serverWrapper.s" server="wrapped-server.s"/>
					</bindings>
				</composite-component>
			</components>
			<bindings>
				<binding client="ClientServerWrapper.m" server="clientWrapper.m"/>
				<binding client="clientWrapper.s" server="serverWrapper.s"/>
			</bindings>
		</composite-component>
	</components>
</componentsDescriptor>
