=== Mykhailenko/programming/src/Extra/org/objectweb/proactive/extra/ressourceallocator/todo.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
					targetNamespace="http://abbeyworkshop.com/todo"
					xmlns="http://abbeyworkshop.com/todo"
					elementFormDefault="qualified"
					attributeFormDefault="unqualified"
>

<xs:simpleType name="nameType">
	<xs:restriction base="xs:string">
		<xs:maxLength value="50" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="itemType">
	<xs:restriction base="xs:string">
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="listType">
	<xs:sequence>
		<xs:element name="item" type="itemType" minOccurs="1" maxOccurs="unbounded" />
	</xs:sequence>
	<xs:attribute name="name" type="nameType" />
</xs:complexType>

<xs:complexType name="todoType">
	<xs:sequence>
		<xs:element name="list" type="listType" minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>
</xs:complexType>

<xs:element name="todo" type="todoType" />

</xs:schema>

=== Mykhailenko/programming/src/Extra/org/objectweb/proactive/extra/ressourceallocator/todoBad.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!-- A Todo List -->
<todo xmlns="http://abbeyworkshop.com/todo"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://abbeyworkshop.com/todo todo.xsd"
>
	<list name="List1">
		<item attrib="text">Item 1</item><!-- Attrib not allowed -->
		<item>Item 2</item>
		<item>Item 3</item>
		<bad>Some text </bad> <!-- Undefined tag -->
	</list>
	<list name="List2">
		<item>Item one</item>
		<item>Item two</item>
		<item attrib="text">Item three</item>
		<item>Item 4</item>
	</list>
	<bad>Some text </bad> <!-- Undefined tag -->
</todo>

=== Mykhailenko/programming/src/Extra/org/objectweb/proactive/extra/ressourceallocator/todo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!-- <!DOCTYPE todo SYSTEM "todo.dtd"> -->
<!-- A Todo List -->
<todo xmlns="http://abbeyworkshop.com/todo"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://abbeyworkshop.com/todo todo.xsd"
>
	<list name="List1">
		<item>Item 1</item>
		<item>Item 2</item>
		<item>Item 3</item>
	</list>
	<list name="List2">
		<item>Item one</item>
		<item>Item two</item>
		<item>Item three</item>
	</list>
</todo>
