=== Mykhailenko/programming/src/Extra/org/objectweb/proactive/extra/ressourcemanager/schema/DeploymentDescriptorSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www-sop.inria.fr/oasis/ProActive/schemas/DeploymentDescriptorSchema"
	xmlns:pa="http://www-sop.inria.fr/oasis/ProActive/schemas/DeploymentDescriptorSchema"
	elementFormDefault="qualified">

	<complexType name="variableType">
		<attribute name="name">
			<simpleType>
				<restriction base="string"></restriction>
			</simpleType>
		</attribute>
		<attribute name="value">
			<simpleType>
				<restriction base="string"></restriction>
			</simpleType>
		</attribute>
	</complexType>

	<complexType name="environmentType">
		<sequence>
			<element name="descriptorVariable" type="pa:variableType" minOccurs="0"
				maxOccurs="unbounded">
			</element>
			<element name="javaPropertyVariable" type="pa:variableType" minOccurs="0"
				maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>

	<simpleType name="nameType">
		<restriction base="string">
			<pattern value="[a-zA-Z_.]+" />
		</restriction>
	</simpleType>

	<simpleType name="pathElementType">
		<annotation>
			<documentation>
				A path to a jar or a directory
			</documentation>
		</annotation>
		<restriction base="string">
			<whiteSpace value="collapse"></whiteSpace>
		</restriction>
	</simpleType>

	<complexType name="shType">
		<sequence>
			<element name="environment" type="pa:environmentType"
				maxOccurs="1" minOccurs="0">
			</element>
		</sequence>
		<attribute name="name" type="pa:nameType"></attribute>
		<attribute name="hostname" type="pa:nameType"></attribute>
		<attribute name="domain" type="pa:nameType"></attribute>
		<attribute name="username" type="pa:nameType"></attribute>
		<attribute name="commandPath" type="pa:pathElementType"></attribute>
		<attribute name="jvmPerHost" type="integer"></attribute>
	</complexType>

	<complexType name="sshType">
		<complexContent>
			<extension base="pa:shType">
				<sequence>
					<element name="privateKey"
						type="pa:pathElementType" minOccurs="0">
					</element>
				</sequence>
				<attribute name="commandOptions" type="string"></attribute>
				<attribute name="hostList" type="string"></attribute>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="rshType">
		<complexContent>
			<extension base="pa:shType"></extension>
		</complexContent>
	</complexType>

	<complexType name="peerSetType"></complexType>
	<complexType name="p2pType">
		<sequence>
			<element name="peerSet" type="pa:peerSetType"></element>
		</sequence>
		<attribute name="nodesAsked" type="positiveInteger"></attribute>
	</complexType>

	<complexType name="lookupType">
		<attribute name="type">
			<simpleType>
				<restriction base="string">
					<enumeration value="RMI"></enumeration>
					<enumeration value="HTTP"></enumeration>
					<enumeration value="IBIS"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="hostlist" type="string"></attribute>
		<attribute name="port" type="positiveInteger"></attribute>
	</complexType>

	<complexType name="acquisitionType">
		<sequence>
			<element name="lookup" type="pa:lookupType" minOccurs="0"></element>
			<element name="p2p" type="pa:p2pType" minOccurs="0"></element>
		</sequence>
	</complexType>

	<simpleType name="refType">
		<restriction base="string">
			<whiteSpace value="collapse"></whiteSpace>
		</restriction>
	</simpleType>

	<complexType name="applicationType">
		<attribute name="ref" type="pa:refType"></attribute>
	</complexType>

	<complexType name="dispatcherType">
		<sequence>
			<element name="application" type="pa:applicationType"
				maxOccurs="unbounded">
			</element>
		</sequence>
		<attribute name="ref" type="pa:refType"></attribute>
	</complexType>

	<complexType name="bridgeType">
		<sequence>
			<element name="application" type="pa:applicationType"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="dispatcher" type="pa:dispatcherType"
				minOccurs="0" maxOccurs="unbounded">
			</element>
			<element name="bridge" type="pa:bridgeType" minOccurs="0"
				maxOccurs="unbounded">
			</element>
		</sequence>
		<attribute name="ref" type="pa:refType"></attribute>
		<attribute name="relay" type="string"></attribute>
	</complexType>

	<complexType name="toolType">
		<attribute name="name" type="string"></attribute>
		<attribute name="path" type="pa:pathElementType"></attribute>
		<attribute name="version" type="string"></attribute>
	</complexType>

	<complexType name="toolsType">
		<sequence>
			<element name="tool" type="pa:toolType"
				maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>

	<complexType name="hostType">
		<sequence>
			<element name="tools" type="pa:toolsType"></element>
		</sequence>
		<attribute name="name" type="string"></attribute>
		<attribute name="homeDirectory" type="pa:pathElementType"></attribute>
	</complexType>

	<complexType name="hostPropertiesType">
		<sequence>
			<element name="host" type="pa:hostType"></element>
		</sequence>
	</complexType>

	<complexType name="deployersType">
		<sequence>
			<element name="ssh" type="pa:sshType" minOccurs="0"
				maxOccurs="unbounded">
			</element>
			<element name="rsh" type="pa:rshType" minOccurs="0"
				maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>

	<complexType name="infrastructureType">
		<sequence>
			<element name="hostProperties" type="pa:hostPropertiesType"
				minOccurs="0">
			</element>
			<element name="dispatchers" type="pa:deployersType"
				minOccurs="0">
			</element>
			<element name="bridges" type="pa:deployersType"
				minOccurs="0">
			</element>
		</sequence>
	</complexType>

	<complexType name="launchType">
		<sequence>
			<element name="application" type="pa:applicationType"
				minOccurs="0" maxOccurs="unbounded">
			</element>
			<element name="dispatcher" type="pa:dispatcherType"
				minOccurs="0" maxOccurs="unbounded">
			</element>
			<element name="bridge" type="pa:bridgeType" minOccurs="0"
				maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>

	<element name="GCMDeployment">
		<complexType>
			<sequence>
				<element name="environment" type="pa:environmentType"
					minOccurs="0">
				</element>
				<element name="acquisition" type="pa:acquisitionType"
					minOccurs="0">
				</element>
				<element name="launch" type="pa:launchType"
					minOccurs="0">
				</element>
				<element name="infrastructure"
					type="pa:infrastructureType" minOccurs="0">
				</element>
			</sequence>
		</complexType>
	</element>

</schema>

=== Mykhailenko/programming/src/Extra/org/objectweb/proactive/extra/ressourcemanager/testfiles/deployment_sample_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<GCMDeployment
	xmlns="http://www-sop.inria.fr/oasis/ProActive/schemas/DeploymentDescriptorSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www-sop.inria.fr/oasis/ProActive/schemas/DeploymentDescriptorSchema ../schema/DeploymentDescriptorSchema.xsd">

	<environment>
		<!-- 
			Uniquement JavaPropertiesVariable et descriptorVariable
		-->
		<descriptorVariable name="foo" value="bar" />
		<javaPropertyVariable name="foo" value="bar" />
	</environment>

	<acquisition>
		<lookup type="HTTP" hostlist="host1 host2 host3" port="80" />
		<!-- type = RMI|IBIS|HTTP -->

		<p2p nodesAsked="12">
			<peerSet></peerSet>
		</p2p>

	</acquisition>

	<launch>

		<!-- Demarre deux JVMS sur la machine courante -->
		<application ref="PAJVM" />
		<application ref="PAJVM" />

		<!-- Demarre une JVM sur chaque machine du LAN -->
		<dispatcher ref="LAN_INRIA">
			<application ref="PAJVM" />
		</dispatcher>

		<!-- Demarre une JVM sur sea -->
		<bridge ref="GW_INRIA">
			<application ref="PAJVM" />
		</bridge>

		<!-- Demarre une JVM sur sea -->
		<bridge ref="GW_INRIA">
			<application ref="PAJVM" />
			<application ref="PAJVM" />
		</bridge>

		<!-- connexion a sea, puis lancement d'une JVM sur chaque machine du LAN -->
		<bridge ref="GW_INRIA">
			<dispatcher ref="LAN_INRIA">
				<application ref="PAJVM" />
			</dispatcher>
		</bridge>

		<!--  -->
		<bridge ref="sea" relay="PAJVM">
			<!-- Utilisation du scheduler local pour lancer une JVM sur X machine du cluster -->
			<dispatcher ref="grid5000">
				<application ref="PAJVM" />
			</dispatcher>
			
			<bridge ref="nef">
				<dispatcher ref="nef">
					<application ref="PAJVM" />
				</dispatcher>
			</bridge>
			<bridge ref="grid5000">
				<dispatcher ref="grid5000">
					<application ref="PAJVM" />
				</dispatcher>
			</bridge>
		</bridge>

	</launch>

	<infrastructure>

		<dispatchers>

			<ssh name="LAN_INRIA"
				hostList="cheypa duff schubby node-[000-100]" domain="inria.fr"
				username="cmathieu" commandPath="/usr/local/bin/ssh"
				jvmPerHost="2">
				<environment>
					<descriptorVariable name="" value="" />
				</environment>

			</ssh>

		</dispatchers>

		<bridges>

			<ssh name="GW_INRIA" hostname="sea" username="cmathieu"
				commandPath="/usr/bin/ssh" commandOptions="">
				<environment>
					<descriptorVariable name="" value="" />
				</environment>
				<privateKey>/home/cmathieu/.ssh/identity</privateKey>
			</ssh>

		</bridges>
	</infrastructure>
</GCMDeployment>
